name: Build Executables

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: 
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    # ---------------------------------------------
    # WINDOWS BUILD
    # ---------------------------------------------
    - name: Build Windows EXE
      if: matrix.os == 'windows-latest'
      run: pyinstaller --onefile --windowed --icon="rosettaicon.ico" --name "Rosetta Magazine Researcher" --add-data "app/templates;app/templates" --hidden-import=yaml app.py

    - name: Upload Windows File
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executable
        path: dist/*.exe

    # ---------------------------------------------
    # MAC BUILD
    # ---------------------------------------------
    - name: Build Mac
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --windowed --name "Rosetta_Magazine_Researcher" --add-data "app/templates:app/templates" --hidden-import=yaml app.py
        cd dist
        zip -r Rosetta_Magazine_Researcher_Mac.zip Rosetta_Magazine_Researcher.app

    - name: Upload Mac File
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Mac-Executable
        path: dist/Rosetta_Magazine_Researcher_Mac.zip

    # ---------------------------------------------
    # LINUX BUILD
    # ---------------------------------------------
    - name: Build Linux
      if: matrix.os == 'ubuntu-latest'
      run: pyinstaller --onefile --windowed --name "Rosetta_Magazine_Researcher" --add-data "app/templates:app/templates" --hidden-import=yaml app.py

    - name: Upload Linux File
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Linux-Executable
        path: dist/Rosetta_Magazine_Researcher
